include("${CMAKE_CURRENT_SOURCE_DIR}/cmake/functions.cmake")

file(
    GLOB_RECURSE SOURCES_CPP
    RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
    src/*.c*
)
file(
    GLOB_RECURSE SOURCES_SHADERS
    RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
    shaders/*
)
set(RESOURCES_FILE "resources.qrc")

resolve_env_or_var(QT_ROOT_DIR "" QT_INSTALL_DIR)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_PREFIX_PATH "${QT_INSTALL_DIR};${CMAKE_PREFIX_PATH}")
set(QT_QML_GENERATE_QMLLS_INI ON)

resolve_env_or_var(QT_QML_SOURCES "${CMAKE_SOURCE_DIR}/qml" QML_SOURCES_PATHS)
append_env_path(QT_PLUGIN_PATH "${QT_INSTALL_DIR}/plugins")
append_env_path(QML2_IMPORT_PATH "${QT_INSTALL_DIR}/qml")
prepend_env_path(LD_LIBRARY_PATH "${QT_INSTALL_DIR}/lib")
prepend_env_path(PATH "${QT_INSTALL_DIR}/bin")

set(CMAKE_ENVIRONMENT_PATH_INSTALL "${QT_INSTALL_DIR}/bin")
set(QT_INSTALL_QML "${QT_INSTALL_DIR}/qml")
set(QT_INSTALL_PLUGINS "${QT_INSTALL_DIR}/plugins")

resolve_env_or_var(VERSION_TAG "0.0.0" PROJECT_VERSION)
resolve_env_or_var(BUILD_TIME "" PROJECT_BUILD_TIME)
resolve_env_or_var(BUILD_NAME "" PROJECT_BUILD_NAME)
add_definitions(-DVERSION_TAG="${PROJECT_VERSION}")
add_definitions(-DBUILD_TIME="${PROJECT_BUILD_TIME}")
add_definitions(-DBUILD_NAME="${PROJECT_BUILD_NAME}")

if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    add_definitions(-DDEBUG_BUILD)
endif ()

find_program(CCACHE_FOUND ccache)
if (CCACHE_FOUND)
    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
    message(STATUS "Using ccache")
endif ()

message(STATUS "QT_INSTALL_DIR=${QT_INSTALL_DIR}")
message(STATUS "QML_SOURCES_PATHS=${QML_SOURCES_PATHS}")
message(STATUS "QT_PLUGIN_PATH=$ENV{QT_PLUGIN_PATH}")
message(STATUS "QML2_IMPORT_PATH=$ENV{QML2_IMPORT_PATH}")
message(STATUS "LD_LIBRARY_PATH=$ENV{LD_LIBRARY_PATH}")
message(STATUS "PATH=$ENV{PATH}")
message(STATUS "EMSCRIPTEN=${EMSCRIPTEN}")
message(STATUS "CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}")
message(STATUS "CMAKE_ENVIRONMENT_PATH_INSTALL=${CMAKE_ENVIRONMENT_PATH_INSTALL}")
message(STATUS "QT_INSTALL_QML=${QT_INSTALL_QML}")
message(STATUS "QT_INSTALL_PLUGINS=${QT_INSTALL_PLUGINS}")
message(STATUS "VERSION_TAG=${PROJECT_VERSION}")
message(STATUS "BUILD_TIME=${PROJECT_BUILD_TIME}")
message(STATUS "BUILD_NAME=${PROJECT_BUILD_NAME}")
message(STATUS "CMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}")
message(STATUS "CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}")
message(STATUS "Qt6_DIR=${Qt6_DIR}")
message(STATUS "CMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}")
message(STATUS "VCPKG_CHAINLOAD_TOOLCHAIN_FILE=${VCPKG_CHAINLOAD_TOOLCHAIN_FILE}")
message(STATUS "VCPKG_TARGET_TRIPLET=${VCPKG_TARGET_TRIPLET}")
